CREDIT_ENRICHER_QUEUE="credit_enricher_queue"
BANK_ENRICHER_QUEUE="bank_enricher_queue"
RECIPIENT_LIST_QUEUE="recipient_list_queue"

DANSKEBANK_TRANSLATOR_QUEUE="danskebank_translator_queue"
NORDEA_TRANSLATOR_QUEUE="nordea_translator_queue"
NYTKREDIT_TRANSLATOR_QUEUE="nytkredit_translator_queue"
BDO_TRANSLATOR_QUEUE="bdo_translator_queue"

DANSKEBANK_REQUEST_QUEUE="danskebank_request_queue"
NORDEA_REQUEST_QUEUE="nordea_request_queue"
NYTKREDIT_REQUEST_QUEUE="nytkredit_request_queue"
BDO_REQUEST_QUEUE="bdo_request_queue"

NORMALIZER_QUEUE="normalizer_queue"
AGGREGATOR_QUEUE="aggregator_queue"
RESPONSE_QUEUE="response_queue"
